export const DUMMY_DATA = {
  pageSize: 5,
  pageNumber: 1,
  totalRegisters: 15,
  list: [
    {
      id: 1,
      userId: 1,
      lawyerId: 1,
      dateStart: new Date('2025-01-10T09:00:00Z'),
      dateEnd: new Date('2025-01-10T10:00:00Z'),
      available: true,
      lawyer: {
        id: 1,
        firstName: 'Juan',
        secondName: 'Pérez',
        speciality: 'Laboral',
        email: 'juan.perez@example.com',
        phone: '123456789',
        active: true,
      },
    },
    {
      id: 2,
      userId: 2,
      lawyerId: 2,
      dateStart: new Date('2025-01-11T11:00:00Z'),
      dateEnd: new Date('2025-01-11T12:00:00Z'),
      available: false,
      lawyer: {
        id: 2,
        firstName: 'Ana',
        secondName: 'Gómez',
        speciality: 'Familiar',
        email: 'ana.gomez@example.com',
        phone: '987654321',
        active: true,
      },
    },
    {
      id: 3,
      userId: 3,
      lawyerId: 3,
      dateStart: new Date('2025-01-12T13:00:00Z'),
      dateEnd: new Date('2025-01-12T14:00:00Z'),
      available: true,
      lawyer: {
        id: 3,
        firstName: 'Luis',
        secondName: 'Martínez',
        speciality: 'Penal',
        email: 'luis.martinez@example.com',
        phone: '555666777',
        active: false,
      },
    },
    {
      id: 4,
      userId: 4,
      lawyerId: 4,
      dateStart: new Date('2025-01-13T15:00:00Z'),
      dateEnd: new Date('2025-01-13T16:00:00Z'),
      available: true,
      lawyer: {
        id: 4,
        firstName: 'María',
        secondName: 'López',
        speciality: 'Civil',
        email: 'maria.lopez@example.com',
        phone: '444555666',
        active: true,
      },
    },
    {
      id: 5,
      userId: 5,
      lawyerId: 5,
      dateStart: new Date('2025-05-14T17:00:00Z'),
      dateEnd: new Date('2025-06-14T18:00:00Z'),
      available: false,
      lawyer: {
        id: 5,
        firstName: 'Perona Perez',
        secondName: 'Ramírez',
        speciality: 'Mercantil',
        email: 'carlos.ramirez@example.com',
        phone: '111222333',
        active: true,
      },
    },
    // Nuevos registros dentro del rango de un mes desde hoy
    {
      id: 6,
      userId: 6,
      lawyerId: 6,
      dateStart: new Date(),
      dateEnd: new Date(new Date().setHours(new Date().getHours() + 1)),
      available: true,
      lawyer: {
        id: 6,
        firstName: 'Sofía',
        secondName: 'Hernández',
        speciality: 'Laboral',
        email: 'sofia.hernandez@example.com',
        phone: '123123123',
        active: true,
      },
    },
    {
      id: 7,
      userId: 7,
      lawyerId: 7,
      dateStart: new Date(new Date().setDate(new Date().getDate() + 5)),
      dateEnd: new Date(new Date().setDate(new Date().getDate() + 5)),
      available: true,
      lawyer: {
        id: 7,
        firstName: 'Pedro',
        secondName: 'García',
        speciality: 'Penal',
        email: 'pedro.garcia@example.com',
        phone: '321321321',
        active: true,
      },
    },
    {
      id: 8,
      userId: 8,
      lawyerId: 8,
      dateStart: new Date(new Date().setDate(new Date().getDate() + 10)),
      dateEnd: new Date(new Date().setDate(new Date().getDate() + 10)),
      available: true,
      lawyer: {
        id: 8,
        firstName: 'Carla',
        secondName: 'Torres',
        speciality: 'Civil',
        email: 'carla.torres@example.com',
        phone: '999888777',
        active: true,
      },
    },
    {
      id: 9,
      userId: 9,
      lawyerId: 9,
      dateStart: new Date(new Date().setDate(new Date().getDate() + 15)),
      dateEnd: new Date(new Date().setDate(new Date().getDate() + 15)),
      available: true,
      lawyer: {
        id: 9,
        firstName: 'Lucía',
        secondName: 'Morales',
        speciality: 'Familiar',
        email: 'lucia.morales@example.com',
        phone: '888777666',
        active: true,
      },
    },
    {
      id: 10,
      userId: 10,
      lawyerId: 10,
      dateStart: new Date(new Date().setDate(new Date().getDate() + 20)),
      dateEnd: new Date(new Date().setDate(new Date().getDate() + 20)),
      available: true,
      lawyer: {
        id: 10,
        firstName: 'José',
        secondName: 'Rojas',
        speciality: 'Mercantil',
        email: 'jose.rojas@example.com',
        phone: '777666555',
        active: true,
      },
    },
  ],
};
